version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:16.20

    steps:
      - checkout
      - run: npm install
      - run: npm run lint

workflows:
  version: 2
  lint-workflow:
    jobs:
      - lint:
          filters:
            branches:
              ignore: /.*/
            pull_requests:
              only: /.*/