version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:16.20

    steps:
      - checkout
      - run:
          name: Skip if not PR and not main
          command: |
            if [ -z "$CIRCLE_PULL_REQUEST" ] && [ "$CIRCLE_BRANCH" != "circleci-project-setup" ]; then
              circleci step halt
            fi
      - run: npm install
      - run: npm run lint

workflows:
  version: 2
  lint-workflow:
    jobs:
      - lint
          
                